### ISSUE TITLE
Adding sorting bookmarks

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#1]

**Comment by gemguardian** [comment]
@luukverhoeven could you please let me know how much time it would be to add this feature to M4.1/php8

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/itil/changes/153" target="_blank">153</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/itil/changes/153" target="_blank">#153</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by luukverhoeven** [comment]
@gemguardian How should the sorting work? Is this drag-drop javascript or with arrows icons moving the positions?

**Comment by gemguardian** [comment]
@luukverhoeven let's keep it simple, arrows icons moving the positions

**Comment by luukverhoeven** [comment]
The estimated time required to add this feature is three hours.

**Comment by gemguardian** [comment]
@luukverhoeven approved

**Comment by luukverhoeven** [comment]
@gemguardian Aanpassing staat klaar in https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/tree/8677fr957-sorting-bookmarks

Kun je controleren of dit naar wens werkt?

![2023-03-02_10-40-51 (1)](https://user-images.githubusercontent.com/995760/222391528-d825d5c3-4ecb-4903-a697-6fa2b2f9d05b.gif)

**Comment by gemguardian** [comment]
@luukverhoeven klopt het dat als je nu een pagina toegevoegd, dat je eerst je pagina moet refreshen vóórdat je kan verschuiven?

**Comment by luukverhoeven** [comment]
Dit issue is opgelost in de laatste versie https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/tree/8677fr957-sorting-bookmarks

Kun je dit bevestigen?

**Comment by gemguardian** [comment]
@luukverhoeven nadat ik deze versie updaten kreeg ik problemen met het ladeblok in M4.1.1+ (build 202303030) thema Boost 

Het ladeblok wil niet meer open of sluiten op de pagina waar het staat
De console geeft de onderstaande melding

![image](https://user-images.githubusercontent.com/16559999/224419665-335c1b63-5fae-4c16-989b-7ef0dc44bd3c.png)

**Comment by luukverhoeven** [comment]
@gemguardian Dit heb ik zojuist bekeken, maar kon het niet reproduceren. In de error lijkt het te gaan om `fastnav` ipv `user_favorites`

Zijn er bepaalde acties die je uitvoert? Welke versies heb je geïnstalleerd van deze twee plug-ins?

![image](https://user-images.githubusercontent.com/995760/224503626-ecbadb37-31f1-4546-bee4-99b07f738f9a.png)
![image](https://user-images.githubusercontent.com/995760/224503658-b5d11a72-46aa-4b26-be7a-3bc84a08c898.png)
![image](https://user-images.githubusercontent.com/995760/224503736-a13c0098-a024-45e4-adfd-6f59276c51dc.png)

**Comment by gemguardian** [comment]
@luukverhoeven ik had deze versies die jij heb hebt geïnstalleerd. Ik heb Fast Navigation verwijderd, cache clear gedaan maar ik krijg nog steeds dezelfde melding

![image](https://user-images.githubusercontent.com/16559999/224637755-36784160-4351-4403-be32-15792f60aecb.png)

**Comment by luukverhoeven** [comment]
@gemguardian Zie hierbij mijn schermopname. Gek genoeg kom bij mij geen `tooltip` error voorbij.
https://app.screencast.com/H7kvIItTv8ovh

Als ik zoek in de broncode van deze plug-in, zie ik geen tooltip voorbij komen. 

![image](https://user-images.githubusercontent.com/995760/224643832-1e9948d9-66e1-4e44-859e-93843d32ca81.png)

**Comment by gemguardian** [comment]
heel apart. Omdat je tooltip aangaf, dacht ik misschien is het de aanpassing in VSF dat loopt te vervelen. Maar die gede-installeerd en dat lost het nog niet op. 

Enige dat ik zo kan bedenken is een conflict met een andere plugin...

**Comment by gemguardian** [comment]
Okay het is een plugin conflict . want op een andere 4.1 installatie heb ik het issue niet (ook niet op verschillende servers). Nu wordt het dus uitpuzzelen welke plugin het is.

**Comment by gemguardian** [comment]
Ok dit was heel apart - bij een ander account werkte het wel en toen ik dus een startpagina reset deed was het opgelost

**Comment by gemguardian** [comment]
@luukverhoeven akkoord kan door naar MAIN

**Comment by luukverhoeven** [comment]
@gemguardian Doorgezet naar de hoofdbranch en gepubliceerd
