### ISSUE TITLE
Moodle 4.0 - PHP 8 error 

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#11]
Error reported on Moodle.org: https://moodle.org/plugins/block_user_favorites
---------
Moodle 4, PHP8

Debug info:
Error code: generalexceptionmessage
Stack trace:

line 81 of /blocks/user_bookmarks/block_user_bookmarks.php: Error thrown
line 478 of /blocks/moodleblock.class.php: call to block_user_bookmarks->specialization()
line 2091 of /lib/blocklib.php: call to block_base->_load_instance()
line 1097 of /lib/blocklib.php: call to block_instance()
line 1258 of /lib/blocklib.php: call to block_manager->create_block_instances()
line 1145 of /lib/blocklib.php: call to block_manager->ensure_instances_exist()
line 1649 of /lib/pagelib.php: call to block_manager->create_all_block_instances()
line 1110 of /lib/pagelib.php: call to moodle_page->starting_output()
line 1391 of /lib/outputrenderers.php: call to moodle_page->set_state()
line 121 of /index.php: call to core_renderer->header()

I have removed the User Bookmarks block from all tabs and now it is fine. It seems that this is the problem creating the error.

**Comment by Seahawk59** [comment]
I see this error is reported. Will then wait for 4.1 updated version.
Thanks.

**Comment by gemguardian** [comment]
@luukverhoeven Can you check this please? I just did a test on my Moodle 4.1 / Boost and I did not get the PHP error with PHP 8.0 - Maybe it was an early moodle issue. But just to be sure.

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/itil/changes/153" target="_blank">153</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/itil/changes/153" target="_blank">#153</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by luukverhoeven** [comment]
@Seahawk59 We were able to successfully test the plugin on M4.1 / PHP8.0 without any issues. However, in order to provide more detailed information and assist in resolving the reported issue, we kindly request that you provide additional details on how to reproduce the issue.

Can you provide step-by-step instructions, including any relevant error messages or screenshots, so that we can accurately replicate the issue and work towards a solution?

![image](https://user-images.githubusercontent.com/995760/220632489-9aed2f2b-5317-4e87-8364-4ceb90cf5916.png)

**Comment by gemguardian** [comment]
closing issue as not reproducable as well no respondse. Please reopen if necessary.
