### ISSUE TITLE
Moodle 4.6 | Core changes to External API

### ISSUE THREAD

**Issue by gemguardian** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#12]
@luukverhoeven je mag deze wat mij betreft inplannen voor Q3 - dit heeft geen haast mijn inziens omdat 4.1 nog prima werkt

Move lib/externallib.php to namespaced classes and fix coding style, etc.)
https://tracker.moodle.org/browse/MDL-76583

moodle-block-user_favorites: /externallib.php

Mijn indicatie is niet meer dan 1h per plugin.
Plus het uitgevoerde onderzoek van 1h.

**Comment by luukverhoeven** [comment]
Ingepland voor 31 maart.

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/itil/changes/154" target="_blank">154</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/itil/changes/154" target="_blank">#154</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by luukverhoeven** [comment]
Doorgezet naar `master` branch, als het goed is staat ook de verandering van #13 nu er correct erin. 
Als dit goed werkt, zal ik het dan doorzetten naar Moodle?

**Comment by gemguardian** [comment]
@luukverhoeven graag bedankt

**Comment by luukverhoeven** [comment]
Doorgezet naar Moodle.org
