### ISSUE TITLE
Moodle 4.1 and PHP8 error

### ISSUE THREAD

**Issue by Seahawk59** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#15]
Moodle 4, PHP8

Debug info:
Error code: generalexceptionmessage
Stack trace:

line 81 of /blocks/user_bookmarks/block_user_bookmarks.php: Error thrown
line 478 of /blocks/moodleblock.class.php: call to block_user_bookmarks->specialization()
line 2091 of /lib/blocklib.php: call to block_base->_load_instance()
line 1097 of /lib/blocklib.php: call to block_instance()
line 1258 of /lib/blocklib.php: call to block_manager->create_block_instances()
line 1145 of /lib/blocklib.php: call to block_manager->ensure_instances_exist()
line 1649 of /lib/pagelib.php: call to block_manager->create_all_block_instances()
line 1110 of /lib/pagelib.php: call to moodle_page->starting_output()
line 1391 of /lib/outputrenderers.php: call to moodle_page->set_state()
line 121 of /index.php: call to core_renderer->header()

I have removed the User Bookmarks block from all tabs and now it is fine. It seems that this is the problem creating the error.

**Comment by gemguardian** [comment]
@Seahawk59 which version of the block did you use? 2023032200 ? 
Because I could not replicate this issue on my 4.1/ php 8

@luukverhoeven can you check if the correct version is on Moodle.org?

**Comment by Seahawk59** [comment]
@gemguardian It seems that it was an issue when we started with 4.1 on 2020111400. See that the new one on 2023032200 works as expected. It was actually addressed. Thank you. @luukverhoeven

**Comment by gemguardian** [comment]
@Seahawk59 no problem, happy to hear it is not showing for you anymore. And happy to hear our plugin is being used :)
