### ISSUE TITLE
Block drawer breaks in Moodle 4.1 

### ISSUE THREAD

**Issue by stopfstedt** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#16]
Hey there,
I was assessing this plugin for possible addition to our Moodle 4 instance this morning, and noticed that it breaks the block drawer after switching in and out of Edit Mode. 
This seems to be an intermittent failure - I wasn't able to trigger it reliably every time, but often enough to make it an issue.

The browser console shows the following error (or a variation thereof):

`Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'hide'`

Once the error occurs, I'm unable to open (or close) the blocks drawer.

My stack:
- Moodle 4.1.3 
- Boost theme
- latest Chrome and Firefox

![image](https://user-images.githubusercontent.com/1410427/236562026-bdb3e529-852b-49b8-ad42-1fa473d13836.png)

the error seems to be linked to a JQuery-UI/Bootstrap-related interoperability issue, which has manifested itself in various places in Moodle before (see for example https://tracker.moodle.org/browse/MDL-74459)

**Comment by gemguardian** [comment]
@stopfstedt thank you for looking at this issue. I had the same experience, but we could not track the issue and thought it was related to a conflict of Plugins. 

@luukverhoeven can you put this on your log to pull in when it's ready. Time is on my cost.

**Comment by gemguardian** [comment]
@stopfstedt I did not have the issue with Moodle 4.0 when I tested in last summer. But great if you want to check it again.

**Comment by luukverhoeven** [comment]
@gemguardian, would it be possible to include a section for acknowledging contributors in the readme or changelog? This would give credit to those who have made valuable contributions to the project.

**Comment by gemguardian** [comment]
@luukverhoeven yes please!

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/helpdesk/tickets/16728" target="_blank">16728</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/helpdesk/tickets/16728" target="_blank">#16728</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>
