### ISSUE TITLE
Allow bookmarking with # hash

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#2]

**Comment by gemguardian** [comment]
@luukverhoeven could you please let me know - how much work it would be to add this feature to m4.1/php 8?

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/itil/changes/153" target="_blank">153</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/itil/changes/153" target="_blank">#153</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by luukverhoeven** [comment]
Estimation is 1h to support this feature.

**Comment by gemguardian** [comment]
@luukverhoeven akkoord - graag samen inplannen met https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/issues/12

**Comment by luukverhoeven** [comment]
Ingepland voor 31 maart.

**Comment by luukverhoeven** [comment]
@gemguardian Deze verandering zit als het goed is ook al in de `master` branch. 
Ik zie dat ik dit nog niet had teruggekoppeld. Kun je controleren of dit naar wens werkt?

**Comment by gemguardian** [comment]
werkt! :)
