### ISSUE TITLE
styles.css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#20]
in your styles.css you define a style that could clash with core moodle code or other locations where simliar names are used. 
https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/blob/master/styles.css#L22

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code. 

thanks!

**Comment by gemguardian** [comment]
@danmarsden thank you for addressing this issue. I just noticed a pull request from Catalyst but it does not contain the suggested changes , it would be great if you could provide this as well.

**Comment by danmarsden** [comment]
Hey @gemguardian - our main aim was to get it passing unit tests and our security review so a client could install it - not sure if we'll have time left to send a PR for this one but i did mention it to @SashaAnastasi - would be great if you could review the current PR and merge it if you're happy with the changes! - thanks!

**Comment by gemguardian** [comment]
@danmarsden I informed @luukverhoeven it's okay to check the PR , but he is currently on holiday so I hope he will pick this up next week.

**Comment by luukverhoeven** [comment]
@danmarsden @gemguardian: Thank you for the funding. We've updated `styles.css` at line 22 to use a more specific selector, ensuring it won't conflict with other plugins.
