### ISSUE TITLE
Error: Class "external_api" not found in MOODLE_402

### ISSUE THREAD

**Issue by ewallah** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#24]
```
Error: Class "external_api" not found

blocks/user_favorites/classes/external.php:48
lib/classes/component.php:144
```

The external_api was moved in MOODLE_402_STABLE

```
use core_external\external_api;
use core_external\external_function_parameters;
use core_external\external_single_structure;
use core_external\external_value;
```
or

`use core_external\{external_api, external_function_parameters, external_single_structure, external_value};
`

fixes the error in MOODLE_402_STABLE and MOODLE_403_STABLE

**Comment by gemguardian** [comment]
@ewallah thank you for your feedback. @luukverhoeven could you please let me know the time you need to make a 42 compatable version.

**Comment by luukverhoeven** [comment]
@gemguardian We expect that we can fix and test this in 30 minutes.

**Comment by gemguardian** [comment]
@luukverhoeven aproved

**Comment by gemguardian** [comment]
@luukverhoeven kun je mij aangeven wanneer dit op de planning staat?

**Comment by luukverhoeven** [comment]
@gemguardian We kunnen dit uiterlijk volgende week opleveren. Ik hoop dat dit snel genoeg is.

**Comment by gemguardian** [comment]
@luukverhoeven super dan zorg ik dat iemand het kan controleren.

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/helpdesk/tickets/18918" target="_blank">18918</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/helpdesk/tickets/18918" target="_blank">#18918</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by luukverhoeven** [comment]
@gemguardian https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/pull/25

**Comment by gemguardian** [comment]
@luukverhoeven ik heb gevraagd aan Ronny om het te controleren. We komen daar deze week op terug.

**Comment by gemguardian** [comment]
@luukverhoeven deze is akkoord, ik weet niet goed hoe ik dit moet oppakken zeker niet met https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/issues/26#issuecomment-1819776046
