### ISSUE TITLE
Moodle 4.3 branch

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#30]
@gemguardian, we've just pushed the Moodle 4.3 branch. Could you please confirm if it functions as expected? Here's the link: https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/tree/86bwwnc0a-MOODLE403

**Comment by gemguardian** [comment]
@luukverhoeven akkoord  - neem aan dat dit de nieuwe master wordt? Zet je dit ook door naar Moodle Plugin database? Dat zou fijn zijn.

**Comment by luukverhoeven** [comment]
@gemguardian Bijgewerkt, https://moodle.org/plugins/block_user_favorites
