### ISSUE TITLE
Early bird upgrade M4.4

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#33]
Graag informeren wij jullie over de oplevering van de Moodle plug-in(s) en eventuele aanpassingen die jullie hebben aangevraagd. Zouden jullie de functionaliteit ervan kunnen controleren en nagaan of alles naar verwachting werkt? Eventuele vragen of opmerkingen vernemen wij graag.

Bijgevoegd vinden jullie de links naar de repositories:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/tree/86bwwnckq-MOODLE44

Na jullie testen zien we graag jullie akkoord tegemoet voor het doorvoeren van de wijzigingen naar de main/master branch.

**Comment by gemguardian** [comment]
@luukverhoeven akkoord

**Comment by luukverhoeven** [comment]
@gemguardian Doorgezet, ook op Moodle.org
