### ISSUE TITLE
Favorite button not working when block is docked

### ISSUE THREAD

**Issue by KenFarr** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#4]
If the block is docked, and you click on the "Add favorite" button without undocking it then no window appears. If you undock the block it works perfectly. We are using Moodle 3.6.3 with the "More" theme and this was observed to be the same on both PC and Apple on multiple browsers - firefox, chrome and safari. We do have quite a bit of CSS on the site, so it is possible that the issue is to do with that.

**Comment by gemguardian** [comment]
@KenFarr I just have checked with M4.1 / Boost theme and could not reproduce this item. It could very well a theme related issue.
