### ISSUE TITLE
Trigger Set/Remove favorites

### ISSUE THREAD

**Issue by JuanWCG** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#5]
Is there a way we can trigger or replicate the button used to add/remove favorites. I want to add an "Star" icon next to the page title.

**Comment by luukverhoeven** [comment]
Hi @JuanWCG ,

Sure, you can achieve this in several ways:
- Override the block template in your Moodle theme
  - Template: https://github.com/MFreakNL/moodle-block-user_favorites/blob/MOODLE_35_STABLE/templates/favorites.mustache
  - https://docs.moodle.org/dev/Templates#How_to_I_override_a_template_in_my_theme.3F
- You can use custom CSS styling rules to achieve this
